/**
 * Pipeline Stage — CFG Visualization
 */
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import {
  ReactFlow, Background, Controls, MiniMap,
  type Node, type Edge,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { listProjects, getMetrics } from "@/lib/api";
import { GitBranch, AlertTriangle, ArrowRight } from "lucide-react";
import { useState, useMemo } from "react";
import { PipelineStepHeader, NextStepBanner } from "./pipeline.analyze";

export const Route = createFileRoute("/_authenticated/pipeline/cfg")({
  head: () => ({ meta: [{ title: "CFG Visualization — ObfusShield" }] }),
  component: CFGPage,
});

function CFGPage() {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const { data: projects = [] } = useQuery({ queryKey: ["projects"], queryFn: listProjects });
  const completedProjects = projects.filter((p) => p.status === "completed");

  const { data: metricsData, isLoading } = useQuery({
    queryKey: ["metrics", selectedId],
    queryFn: () => getMetrics(selectedId!),
    enabled: !!selectedId,
  });

  const { nodes, edges } = useMemo(() => {
    const raw = metricsData?.latestJob?.cfgJson ?? null;
    if (!raw) return { nodes: [] as Node[], edges: [] as Edge[] };

    const rawNodes: Node[] = (raw.nodes ?? []).map((n: any, i: number) => ({
      id: n.id,
      data: { label: n.data?.label ?? n.id },
      position: { x: (i % 5) * 210, y: Math.floor(i / 5) * 130 },
      style: {
        background: "oklch(0.18 0.03 260 / 0.9)",
        border: "1px solid oklch(0.66 0.19 256 / 0.4)",
        borderRadius: 8,
        color: "#e2e8f0",
        fontSize: 10,
        fontFamily: "'JetBrains Mono', monospace",
        padding: "5px 9px",
        maxWidth: 160,
        wordBreak: "break-all",
      },
    }));

    const rawEdges: Edge[] = (raw.edges ?? []).map((e: any) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      animated: true,
      style: { stroke: "oklch(0.66 0.19 256 / 0.7)", strokeWidth: 1.5 },
    }));

    return { nodes: rawNodes, edges: rawEdges };
  }, [metricsData]);

  const jobMetrics = metricsData?.latestJob?.metrics;

  return (
    <div className="p-8 max-w-7xl space-y-6">
      <div>
        <PipelineStepHeader step={6} label="CFG Visualization" icon={GitBranch} />
        <p className="mt-1 text-sm text-muted-foreground max-w-2xl">
          Post-obfuscation control-flow graph generated by{" "}
          <code className="font-mono text-xs">opt -dot-cfg</code> on the obfuscated LLVM IR,
          converted to React Flow node/edge format.
        </p>
      </div>

      <div className="grid md:grid-cols-4 gap-6">
        {/* Project selector */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono uppercase tracking-widest text-muted-foreground">
            Protected Projects
          </h2>
          {completedProjects.length === 0 ? (
            <div className="glass rounded-xl p-4 text-sm text-muted-foreground text-center">
              No protected projects.{" "}
              <Link to="/pipeline/obfuscate" className="text-primary hover:underline">
                Run obfuscation
              </Link>
            </div>
          ) : (
            <div className="space-y-1.5">
              {completedProjects.map((p) => (
                <button
                  key={p._id}
                  onClick={() => setSelectedId(p._id)}
                  className={`lift-glow w-full text-left px-3 py-2.5 rounded-xl text-sm transition ${
                    selectedId === p._id
                      ? "bg-primary/10 border border-primary/30 text-foreground"
                      : "glass hover:border-primary/20 text-muted-foreground"
                  }`}
                >
                  <div className="font-medium truncate">{p.name}</div>
                  <div className="text-[10px] font-mono uppercase mt-0.5">{p.language}</div>
                </button>
              ))}
            </div>
          )}

          {/* CFG metrics */}
          {jobMetrics && (
            <div className="space-y-2 mt-4">
              <h3 className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">
                Graph Metrics
              </h3>
              {[
                ["CFG Growth",   `+${jobMetrics.cfgGrowthPct ?? 0}%`],
                ["Complexity",   `+${jobMetrics.complexityIncrease ?? 0}%`],
                ["Entropy +",    `+${jobMetrics.entropyIncrease ?? 0}%`],
                ["Sec. Score",   `${jobMetrics.securityScore ?? 0}`],
              ].map(([l, v]) => (
                <div key={l} className="lift-glow glass rounded-lg px-3 py-2 flex justify-between text-xs">
                  <span className="text-muted-foreground">{l}</span>
                  <span className="font-mono font-semibold text-gradient">{v}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* CFG canvas */}
        <div className="md:col-span-3">
          {!selectedId ? (
            <div className="glass rounded-2xl flex items-center justify-center" style={{ height: 500 }}>
              <div className="text-center">
                <GitBranch className="h-12 w-12 mx-auto text-muted-foreground/20 mb-3" />
                <div className="text-muted-foreground">Select a project to view its CFG</div>
              </div>
            </div>
          ) : isLoading ? (
            <div className="glass rounded-2xl flex items-center justify-center" style={{ height: 500 }}>
              <div className="text-muted-foreground">Loading CFG…</div>
            </div>
          ) : nodes.length === 0 ? (
            <div className="glass rounded-2xl p-12 text-center" style={{ height: 500, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
              <AlertTriangle className="h-10 w-10 text-muted-foreground/30 mb-3" />
              <div className="font-semibold">No CFG data</div>
              <p className="text-sm text-muted-foreground mt-2 max-w-xs">
                The CFG is generated during the LLVM pipeline. The LLVM service must be running
                and Graphviz must be installed.
              </p>
            </div>
          ) : (
            <div className="glass rounded-2xl overflow-hidden border border-border" style={{ height: 520 }}>
              <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-muted/20">
                <div className="text-[10px] font-mono text-muted-foreground">
                  {nodes.length} blocks · {edges.length} edges · post-obfuscation
                </div>
                <div className="text-[10px] font-mono text-[oklch(0.72_0.17_160)]">● Live</div>
              </div>
              <div style={{ height: 480 }}>
                <ReactFlow nodes={nodes} edges={edges} fitView proOptions={{ hideAttribution: true }}>
                  <Background color="oklch(0.66 0.19 256 / 0.06)" gap={24} />
                  <Controls style={{ background: "oklch(0.18 0.03 260)", border: "1px solid oklch(0.66 0.19 256 / 0.2)" }} />
                  <MiniMap style={{ background: "oklch(0.18 0.03 260)" }} nodeColor="oklch(0.66 0.19 256)" />
                </ReactFlow>
              </div>
            </div>
          )}
        </div>
      </div>

      <NextStepBanner
        to="/pipeline/reports"
        label="Next: Generate Report"
        enabled={!!selectedId}
        hint="Compile analysis, metrics, and CFG into an executive PDF report"
      />
    </div>
  );
}
