/**
 * CFG Visualization page — /projects/:id/cfg
 * Shows the before/after control-flow graph using React Flow.
 * Data comes from GET /api/metrics/:projectId → latestJob.cfgJsonPath
 */
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ReactFlow, Background, Controls, MiniMap, type Node, type Edge } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { getMetrics } from "@/lib/api";
import { GitBranch, ArrowLeft, AlertTriangle } from "lucide-react";
import { useMemo } from "react";

export const Route = createFileRoute("/_authenticated/projects/$id/cfg")({
  head: () => ({ meta: [{ title: "CFG — ObfusShield AI" }] }),
  component: CFGPage,
});

function CFGPage() {
  const { id } = Route.useParams();

  const { data, isLoading } = useQuery({
    queryKey: ["metrics", id],
    queryFn: () => getMetrics(id),
  });

  const { nodes, edges } = useMemo(() => {
    const raw = data?.latestJob?.cfgJson ?? null;
    if (!raw) return { nodes: [], edges: [] };

    // Layout nodes in a grid — React Flow needs x/y positions
    const rawNodes: Node[] = (raw.nodes ?? []).map((n: any, i: number) => ({
      id: n.id,
      data: { label: n.data?.label ?? n.id },
      position: { x: (i % 5) * 200, y: Math.floor(i / 5) * 120 },
      style: {
        background: "oklch(0.18 0.03 260)",
        border: "1px solid oklch(0.66 0.19 256 / 0.5)",
        borderRadius: 8,
        color: "#e2e8f0",
        fontSize: 11,
        fontFamily: "monospace",
        padding: "6px 10px",
        maxWidth: 160,
        wordBreak: "break-all",
      },
    }));

    const rawEdges: Edge[] = (raw.edges ?? []).map((e: any) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      animated: true,
      style: { stroke: "oklch(0.66 0.19 256)" },
    }));

    return { nodes: rawNodes, edges: rawEdges };
  }, [data]);

  if (isLoading) {
    return (
      <div className="p-8 text-muted-foreground flex items-center gap-2">
        <span className="animate-spin h-4 w-4 border-2 border-primary border-t-transparent rounded-full" />
        Loading CFG…
      </div>
    );
  }

  return (
    <div className="p-8 max-w-7xl">
      <div className="flex items-center gap-3 mb-6">
        <Link
          to="/projects/$id"
          params={{ id }}
          className="fade-hover inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" /> Back to project
        </Link>
      </div>

      <header className="mb-6">
        <div className="text-xs uppercase tracking-[0.2em] font-mono text-[oklch(0.85_0.1_240)]">
          LLVM Analysis
        </div>
        <h1 className="mt-2 font-display text-3xl font-bold flex items-center gap-2">
          <GitBranch className="h-7 w-7 text-[oklch(0.85_0.1_240)]" />
          Control Flow Graph
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Post-obfuscation CFG — generated by{" "}
          <code className="font-mono text-xs">opt -dot-cfg</code> on the obfuscated LLVM IR.
        </p>
      </header>

      {nodes.length === 0 ? (
        <div className="glass rounded-2xl p-12 text-center">
          <AlertTriangle className="h-10 w-10 mx-auto text-muted-foreground mb-3" />
          <div className="font-semibold">No CFG available</div>
          <p className="text-sm text-muted-foreground mt-2 max-w-md mx-auto">
            Run obfuscation first — the CFG is generated during the LLVM pass pipeline.
            Requires the LLVM service running on Linux/Docker.
          </p>
          <Link
            to="/projects/$id"
            params={{ id }}
            className="trace-border mt-5 inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-4 py-2 text-sm"
          >
            Go back and run obfuscation
          </Link>
        </div>
      ) : (
        <div className="glass rounded-2xl overflow-hidden" style={{ height: 600 }}>
          <ReactFlow
            nodes={nodes}
            edges={edges}
            fitView
            proOptions={{ hideAttribution: true }}
          >
            <Background color="oklch(0.66 0.19 256 / 0.1)" gap={20} />
            <Controls
              style={{ background: "oklch(0.18 0.03 260)", border: "1px solid oklch(0.66 0.19 256 / 0.3)" }}
            />
            <MiniMap
              style={{ background: "oklch(0.18 0.03 260)" }}
              nodeColor="oklch(0.66 0.19 256)"
            />
          </ReactFlow>
        </div>
      )}

      {data?.latestJob?.metrics && (
        <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            ["CFG Growth", `+${data.latestJob.metrics.cfgGrowthPct ?? 0}%`],
            ["Complexity Increase", `+${data.latestJob.metrics.complexityIncrease ?? 0}%`],
            ["Entropy Increase", `+${data.latestJob.metrics.entropyIncrease ?? 0}%`],
            ["Security Score", data.latestJob.metrics.securityScore ?? "—"],
          ].map(([label, value]) => (
            <div key={label} className="lift-glow glass rounded-xl p-4 text-center">
              <div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div>
              <div className="mt-2 text-2xl font-display font-bold text-gradient">{value}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
