/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedPipelineReportsRouteImport } from './routes/_authenticated/pipeline.reports'
import { Route as AuthenticatedPipelineProtectRouteImport } from './routes/_authenticated/pipeline.protect'
import { Route as AuthenticatedPipelineObfuscateRouteImport } from './routes/_authenticated/pipeline.obfuscate'
import { Route as AuthenticatedPipelineDownloadsRouteImport } from './routes/_authenticated/pipeline.downloads'
import { Route as AuthenticatedPipelineCfgRouteImport } from './routes/_authenticated/pipeline.cfg'
import { Route as AuthenticatedPipelineAnalyzeRouteImport } from './routes/_authenticated/pipeline.analyze'
import { Route as AuthenticatedProjectsIdCfgRouteImport } from './routes/_authenticated/projects.$id.cfg'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedPipelineReportsRoute =
  AuthenticatedPipelineReportsRouteImport.update({
    id: '/pipeline/reports',
    path: '/pipeline/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineProtectRoute =
  AuthenticatedPipelineProtectRouteImport.update({
    id: '/pipeline/protect',
    path: '/pipeline/protect',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineObfuscateRoute =
  AuthenticatedPipelineObfuscateRouteImport.update({
    id: '/pipeline/obfuscate',
    path: '/pipeline/obfuscate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineDownloadsRoute =
  AuthenticatedPipelineDownloadsRouteImport.update({
    id: '/pipeline/downloads',
    path: '/pipeline/downloads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineCfgRoute =
  AuthenticatedPipelineCfgRouteImport.update({
    id: '/pipeline/cfg',
    path: '/pipeline/cfg',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineAnalyzeRoute =
  AuthenticatedPipelineAnalyzeRouteImport.update({
    id: '/pipeline/analyze',
    path: '/pipeline/analyze',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdCfgRoute =
  AuthenticatedProjectsIdCfgRouteImport.update({
    id: '/cfg',
    path: '/cfg',
    getParentRoute: () => AuthenticatedProjectsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/pipeline/analyze': typeof AuthenticatedPipelineAnalyzeRoute
  '/pipeline/cfg': typeof AuthenticatedPipelineCfgRoute
  '/pipeline/downloads': typeof AuthenticatedPipelineDownloadsRoute
  '/pipeline/obfuscate': typeof AuthenticatedPipelineObfuscateRoute
  '/pipeline/protect': typeof AuthenticatedPipelineProtectRoute
  '/pipeline/reports': typeof AuthenticatedPipelineReportsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/$id/cfg': typeof AuthenticatedProjectsIdCfgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/pipeline/analyze': typeof AuthenticatedPipelineAnalyzeRoute
  '/pipeline/cfg': typeof AuthenticatedPipelineCfgRoute
  '/pipeline/downloads': typeof AuthenticatedPipelineDownloadsRoute
  '/pipeline/obfuscate': typeof AuthenticatedPipelineObfuscateRoute
  '/pipeline/protect': typeof AuthenticatedPipelineProtectRoute
  '/pipeline/reports': typeof AuthenticatedPipelineReportsRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/$id/cfg': typeof AuthenticatedProjectsIdCfgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/pipeline/analyze': typeof AuthenticatedPipelineAnalyzeRoute
  '/_authenticated/pipeline/cfg': typeof AuthenticatedPipelineCfgRoute
  '/_authenticated/pipeline/downloads': typeof AuthenticatedPipelineDownloadsRoute
  '/_authenticated/pipeline/obfuscate': typeof AuthenticatedPipelineObfuscateRoute
  '/_authenticated/pipeline/protect': typeof AuthenticatedPipelineProtectRoute
  '/_authenticated/pipeline/reports': typeof AuthenticatedPipelineReportsRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/$id/cfg': typeof AuthenticatedProjectsIdCfgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/projects'
    | '/pipeline/analyze'
    | '/pipeline/cfg'
    | '/pipeline/downloads'
    | '/pipeline/obfuscate'
    | '/pipeline/protect'
    | '/pipeline/reports'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/$id/cfg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/projects'
    | '/pipeline/analyze'
    | '/pipeline/cfg'
    | '/pipeline/downloads'
    | '/pipeline/obfuscate'
    | '/pipeline/protect'
    | '/pipeline/reports'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/$id/cfg'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/pipeline/analyze'
    | '/_authenticated/pipeline/cfg'
    | '/_authenticated/pipeline/downloads'
    | '/_authenticated/pipeline/obfuscate'
    | '/_authenticated/pipeline/protect'
    | '/_authenticated/pipeline/reports'
    | '/_authenticated/projects/$id'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/$id/cfg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/pipeline/reports': {
      id: '/_authenticated/pipeline/reports'
      path: '/pipeline/reports'
      fullPath: '/pipeline/reports'
      preLoaderRoute: typeof AuthenticatedPipelineReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline/protect': {
      id: '/_authenticated/pipeline/protect'
      path: '/pipeline/protect'
      fullPath: '/pipeline/protect'
      preLoaderRoute: typeof AuthenticatedPipelineProtectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline/obfuscate': {
      id: '/_authenticated/pipeline/obfuscate'
      path: '/pipeline/obfuscate'
      fullPath: '/pipeline/obfuscate'
      preLoaderRoute: typeof AuthenticatedPipelineObfuscateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline/downloads': {
      id: '/_authenticated/pipeline/downloads'
      path: '/pipeline/downloads'
      fullPath: '/pipeline/downloads'
      preLoaderRoute: typeof AuthenticatedPipelineDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline/cfg': {
      id: '/_authenticated/pipeline/cfg'
      path: '/pipeline/cfg'
      fullPath: '/pipeline/cfg'
      preLoaderRoute: typeof AuthenticatedPipelineCfgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline/analyze': {
      id: '/_authenticated/pipeline/analyze'
      path: '/pipeline/analyze'
      fullPath: '/pipeline/analyze'
      preLoaderRoute: typeof AuthenticatedPipelineAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/cfg': {
      id: '/_authenticated/projects/$id/cfg'
      path: '/cfg'
      fullPath: '/projects/$id/cfg'
      preLoaderRoute: typeof AuthenticatedProjectsIdCfgRouteImport
      parentRoute: typeof AuthenticatedProjectsIdRoute
    }
  }
}

interface AuthenticatedProjectsIdRouteChildren {
  AuthenticatedProjectsIdCfgRoute: typeof AuthenticatedProjectsIdCfgRoute
}

const AuthenticatedProjectsIdRouteChildren: AuthenticatedProjectsIdRouteChildren =
  {
    AuthenticatedProjectsIdCfgRoute: AuthenticatedProjectsIdCfgRoute,
  }

const AuthenticatedProjectsIdRouteWithChildren =
  AuthenticatedProjectsIdRoute._addFileChildren(
    AuthenticatedProjectsIdRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedPipelineAnalyzeRoute: typeof AuthenticatedPipelineAnalyzeRoute
  AuthenticatedPipelineCfgRoute: typeof AuthenticatedPipelineCfgRoute
  AuthenticatedPipelineDownloadsRoute: typeof AuthenticatedPipelineDownloadsRoute
  AuthenticatedPipelineObfuscateRoute: typeof AuthenticatedPipelineObfuscateRoute
  AuthenticatedPipelineProtectRoute: typeof AuthenticatedPipelineProtectRoute
  AuthenticatedPipelineReportsRoute: typeof AuthenticatedPipelineReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedPipelineAnalyzeRoute: AuthenticatedPipelineAnalyzeRoute,
  AuthenticatedPipelineCfgRoute: AuthenticatedPipelineCfgRoute,
  AuthenticatedPipelineDownloadsRoute: AuthenticatedPipelineDownloadsRoute,
  AuthenticatedPipelineObfuscateRoute: AuthenticatedPipelineObfuscateRoute,
  AuthenticatedPipelineProtectRoute: AuthenticatedPipelineProtectRoute,
  AuthenticatedPipelineReportsRoute: AuthenticatedPipelineReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
